### ISSUE TITLE
Update ADAS module to support current Cherab version

### ISSUE THREAD

**Issue by vsnever** [cherab/adas#3]
This module is outdated and cannot be installed with the current version of the Cherab API. I'll try to fix this issue.

**Comment by vsnever** [comment]
I think that since the OpenADAS module is part of the Cherab, the ADAS module can use its API. The ADAS module should extend the functionality of the OpenADAS module, not replace it. With the exception of downloading data files from the OpenADAS server, everything that was created for the OpenADAS module also works with full ADAS. Even when the interface to ADAS603 is added, without all the functionality which OpenADAS module provides, this module will be hard to use.

So, @mattngc, @CnlPepper, @Mateasek, @jacklovell, would it be right to rewrite this module using OpenADAS API (repository, rates, parse, etc)?

**Comment by mattngc** [comment]
Hi @vsnever, I completely agree with you. The OpenADAS module in core is superior. This module should have been updated but has always suffered from a lack of users. No objections if you want to update the API and bring it in line with the  OpenADAS interface in core.

**Comment by jacklovell** [comment]
Fixed by #4
